schema_version = "1.0.0"
id = "send_to_library"
version = "1.0.0"
name = "Send to Library"
tagline = "Send datablocks (like Node Groups) to an external asset library blend file."
maintainer = "jmatthews"
type = "add-on"
blender_version_min = "4.2.0"
license = [
  "SPDX:GPL-3.0-or-later",
]
#website = ""

[permissions]
#network = { optional = true }
files = "All Control"
#clipboard = { optional = true }
